name: example server
platform: github
secret_key: '1'

server:
  address: '0.0.0.0'
  port: 3000
  path: '/webhooks'


on:
  push:
    branches: [ main ]
    trigger: 'deploy'

jobs:
  deploy:
    steps:
